[package]
name = "Talus"
version = "0.0.1"
published-at = "0xa070"
edition = "2024.beta"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
Sui = { local = "../sui-framework" }

[addresses]
talus = "0xa070"
